<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Resume.Data\Resume.Data.csproj" />
    <ProjectReference Include="..\Resume.Contracts\Resume.Contracts.csproj" />
    <ProjectReference Include="..\Resume.ServiceDefaults\Resume.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.2" />
    <PackageReference Include="FastEndpoints" Version="8.3.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5324bcfa-969f-487b-9de6-d830396994a5</UserSecretsId>
  </PropertyGroup>

</Project>
