// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Resume.Data;

#nullable disable

namespace Resume.Data.Migrations
{
    [DbContext(typeof(ResumeDbContext))]
    [Migration("20260827164129_AddPersonalInfoLocationAndRealResumeData")]
    partial class AddPersonalInfoLocationAndRealResumeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Resume.Data.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Details")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Education");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            Degree = "CIS",
                            Details = new string[0],
                            EndDate = new DateOnly(2013, 1, 1),
                            FieldOfStudy = "Database Administration",
                            Institution = "DeVry University",
                            StartDate = new DateOnly(2010, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            Degree = "CIS",
                            Details = new string[0],
                            EndDate = new DateOnly(2005, 1, 1),
                            Institution = "Coleman College",
                            StartDate = new DateOnly(2004, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            Degree = "Telephone/Switchboard Repair Course, Basic Electronics Course, Fundamentals of Leadership Course",
                            Details = new string[0],
                            EndDate = new DateOnly(2000, 1, 1),
                            Institution = "U.S. Marine Corps",
                            StartDate = new DateOnly(1995, 1, 1)
                        });
                });

            modelBuilder.Entity("Resume.Data.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.PrimitiveCollection<string[]>("Highlights")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Experience");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Company = "AFG Companies",
                            Highlights = new[] { "Drove migration of a legacy web application from .NET Framework 4.8 to .NET 8 to completion.", "Supported and enhanced a legacy system to improve stability and performance.", "Supported applications using a mix of MVC, Angular, WebAPI, bootstrap, tailwind, and AWS services.", "Implemented repository, chain-of-responsibility, REPR endpoint, vertical slice, and rule engine design patterns to restructure processing logic.", "Optimized and refactored SQL Server stored procedures to eliminate redundant logic and improve maintainability.", "Consolidated and eliminated redundant API services to streamline processing.", "Wrote Terraform IaC to provision AWS resources, including deployment pipelines, Lambda functions, and ECR/ECS services.", "Configured Route 53 DNS routing rules to ELB instances.", "Designed and developed new REST API services using FastEndpoints, M2M Auth0 authentication, and a PostgreSQL backend." },
                            JobTitle = "Lead/Senior Software Engineer (Hybrid)",
                            StartDate = new DateOnly(2024, 11, 1)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Company = "Harte-Hanks Inc.",
                            EndDate = new DateOnly(2024, 3, 1),
                            Highlights = new[] { "Designed and developed a customer list system using .NET Core 5 and ASP.NET MVC with a PostgreSQL backend, hosted on a Linux server in AWS.", "Built CI/CD pipelines in Azure DevOps for deployment to Azure App Services.", "Supported, migrated, and enhanced automotive lead enrichment services in C# and VB.NET for BMW.", "Designed and developed a multi-channel messaging system for lead transmission to vendors using REST and SOAP with multiple authentication schemes.", "Designed, documented, and developed a Meta Graph API integration to post lead data to a REST endpoint.", "Designed and developed WebAPI and WCF services enabling external vendors to exchange data per STAR automotive specifications.", "Designed and developed internal web applications with 3-tier architecture supporting desktop and mobile layouts.", "Designed and developed an OAuth 2.0 SSO gateway to authenticate legacy applications.", "Developed a mobile web front-end repair system for Lenovo using HTML, JavaScript, and Bootstrap.", "Designed and developed SSIS packages for ETL and file processing.", "Analyzed and optimized database stored procedures to improve response time and reduce processing overhead.", "Migrated MongoDB data to a CentOS server on AWS.", "Designed and developed a dynamic SQL rules engine and internal web application enabling non-developers to configure the lead system.", "Migrated legacy applications to AWS, including IIS and SQL Server setup and database backup/restore operations.", "Created architecture and design documents for new websites, services and feature enhancements.", "Led a team's transition from TFS to Git.", "Led projects coordinating offshore developers, breaking down tasks to enable parallel workstreams.", "Estimated development scope and labor time for projects ranging between 40 and 500 hours." },
                            JobTitle = "Software Engineer III (Remote)",
                            StartDate = new DateOnly(2019, 10, 1)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            Company = "Allied Electronics & Automation",
                            EndDate = new DateOnly(2019, 9, 1),
                            Highlights = new[] { "Developed and maintained a large-scale eCommerce website built with MVC 5, Web Forms, and TypeScript.", "Designed and developed responsive layouts using Foundation.", "Designed, documented, and developed REST API microservices wrapping search engine functionality and product information.", "Created UML use case and sequence diagrams for new system designs and planning.", "Created and maintained CI/CD release pipelines.", "Diagnosed and remedied network issues across Windows servers, F5 load balancers and security gateways.", "Administered IIS and configured new internal websites.", "Trained junior developers on clean architecture and SOLID principles.", "Participated in off-hours system monitoring rotation and critical system maintenance." },
                            JobTitle = "Web Developer",
                            StartDate = new DateOnly(2017, 12, 1)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            Company = "Harte-Hanks Inc.",
                            EndDate = new DateOnly(2017, 10, 1),
                            Highlights = new string[0],
                            JobTitle = "Software Engineer III (Remote)",
                            StartDate = new DateOnly(2012, 4, 1)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            Company = "TekSystems (Contract Employee for BNSF Railroad)",
                            EndDate = new DateOnly(2012, 1, 1),
                            Highlights = new[] { "Designed and developed multi-threaded, scalable Windows services to process custom network communication messages for distributed systems, primarily over TCP/IP using clear, symmetric, and asymmetric cryptography schemes.", "Designed and developed service for securely transferring file data to railroad devices according to third-party specifications.", "Designed and developed services to transfer messages using AMQP technology and route messages from those services to simulate an internal network.", "Designed and developed device simulator for vehicles to communicate with back office over TCP/IP or RS-232 connection.", "Designed and developed C++/CLI modules and wrappers using mixed mode to interface with a hardware cryptographic module." },
                            JobTitle = ".NET Developer (details limited due to NDA)",
                            StartDate = new DateOnly(2011, 6, 1)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333306"),
                            Company = "Stryker Communications",
                            EndDate = new DateOnly(2011, 4, 1),
                            Highlights = new[] { "Developed and supported embedded firmware for lighting control panels.", "Developed test automation application for manufacturing to communicate over RS-232.", "Performed functional and environmental testing on medical devices.", "Created test protocols and reports for electronic and mechanical devices." },
                            JobTitle = "Sr. Lab Technician",
                            StartDate = new DateOnly(2010, 4, 1)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333307"),
                            Company = "GDSX Ltd.",
                            EndDate = new DateOnly(2008, 6, 1),
                            Highlights = new[] { "Designed, developed, and tested a data-bound Windows Forms application for retrieving, editing, and saving multiple field changes in a SQL Server database.", "Supported travel automation software integrating with Apollo, Sabre, and Worldspan GDS systems.", "Developed and maintained ASP.NET and JavaScript report templates using a SQL Server Reporting Services back end.", "Analyzed and coded maintenance fixes for a large-scale travel automation client." },
                            JobTitle = "Software Developer",
                            StartDate = new DateOnly(2007, 6, 1)
                        });
                });

            modelBuilder.Entity("Resume.Data.Entities.PersonalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "jeff.m.proulx@gmail.com",
                            FullName = "Jeffrey M. Proulx",
                            Headline = "Lead/Senior Software Engineer",
                            Location = "Fort Worth, TX",
                            Phone = "940-594-0410",
                            Summary = "Full-stack software engineer with 15+ years of experience designing and modernizing distributed systems, REST APIs, and cloud infrastructure across AWS and Azure. Skilled at leading legacy application migrations, architecting vertical-slice services, and mentoring engineering teams."
                        });
                });

            modelBuilder.Entity("Resume.Data.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
