// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Resume.Data;

#nullable disable

namespace Resume.Data.Migrations
{
    [DbContext(typeof(ResumeDbContext))]
    partial class ResumeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Resume.Data.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Details")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("text");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Education");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            Degree = "B.S.",
                            Details = new[] { "Graduated cum laude", "Teaching assistant for Data Structures" },
                            EndDate = new DateOnly(2018, 5, 1),
                            FieldOfStudy = "Computer Science",
                            Institution = "State University",
                            StartDate = new DateOnly(2014, 9, 1)
                        });
                });

            modelBuilder.Entity("Resume.Data.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.PrimitiveCollection<string[]>("Highlights")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Experience");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Company = "Northwind Traders",
                            Highlights = new[] { "Led migration of a monolithic ASP.NET application to a vertical-slice API architecture.", "Designed and shipped an internal developer platform used by 40+ engineers.", "Mentored 3 junior engineers through structured code review and pairing." },
                            JobTitle = "Senior Software Engineer",
                            Location = "Remote",
                            StartDate = new DateOnly(2022, 3, 1)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Company = "Contoso Software",
                            EndDate = new DateOnly(2022, 2, 1),
                            Highlights = new[] { "Built and maintained a customer-facing React application serving 200k monthly users.", "Introduced automated integration testing, cutting production incidents by 30%." },
                            JobTitle = "Software Engineer",
                            Location = "Seattle, WA",
                            StartDate = new DateOnly(2018, 6, 1)
                        });
                });

            modelBuilder.Entity("Resume.Data.Entities.PersonalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "jordan.rivera@example.com",
                            FullName = "Jordan Rivera",
                            GitHubUrl = "https://github.com/jordanrivera",
                            Headline = "Senior Software Engineer",
                            LinkedInUrl = "https://linkedin.com/in/jordanrivera",
                            Phone = "555-0100",
                            Summary = "Backend-leaning full-stack engineer with 10+ years building distributed systems, developer tooling, and web platforms.",
                            WebsiteUrl = "https://jordanrivera.dev"
                        });
                });

            modelBuilder.Entity("Resume.Data.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Category = "Languages",
                            Name = "C#",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Category = "Languages",
                            Name = "TypeScript",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Category = "Languages",
                            Name = "SQL",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            Category = "Frameworks",
                            Name = "ASP.NET Core",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            Category = "Frameworks",
                            Name = "React",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            Category = "Frameworks",
                            Name = "Blazor",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            Category = "Tools",
                            Name = "Docker",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            Category = "Tools",
                            Name = "Git",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222209"),
                            Category = "Cloud",
                            Name = "Azure",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-22222222220a"),
                            Category = "Cloud",
                            Name = "AWS",
                            SortOrder = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
